### ISSUE TITLE
Corpus

### ISSUE THREAD

**Issue by Salih1234** [cemkod/e-bliss-rapgen#1]
Örnek bir corpusda yayınlayabilir misiniz?

**Comment by cemkod** [comment]
Kullandigimiz corpus telifli sarki sozleri icerdigi icin onu yayinlayamiyorum. Zaten corpusun formati cok onemli degil, yeter ki icerdigi tum parcalarin bicimi birbirine benzesin. ama benim kullandigimdaki format soyle:

> ~
> "Parca adi"
> 
> jasdlfkjasdlkfjsadfas asdfasd fsd fdsaf sdaf
> a sfasdfas dfa sfsadf sd
>  fsadf asdfsadf
>  asdf asd
> 
>  asdf sdaf
>  sadfasd fs
>  fsadf asdfsdf 
> adfas dfasd f
>  asdfasdf a
> ~
> "Parca adi"
> 
> ...
>
